# Generated by Django 5.2.11 on 2026-02-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('bot', 'Bot'), ('client', 'Client'), ('admin', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('pending_admin_reply', 'Pending Admin Reply')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('subheadline', models.TextField()),
                ('primary_btn_text', models.CharField(max_length=50)),
                ('primary_btn_link', models.CharField(max_length=200)),
                ('secondary_btn_text', models.CharField(max_length=50)),
                ('secondary_btn_link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='ValueLadderOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('opt1_title', models.CharField(max_length=100)),
                ('opt1_description', models.TextField()),
                ('opt1_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opt1_text', models.TextField()),
                ('opt1_btn_text', models.CharField(max_length=50)),
                ('opt2_title', models.CharField(max_length=100)),
                ('opt2_description', models.TextField()),
                ('opt2_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opt2_text_1', models.CharField(max_length=255)),
                ('opt2_text_2', models.CharField(max_length=255)),
                ('opt2_guarantee', models.TextField()),
                ('opt2_btn_text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Value Ladder Offers',
            },
        ),
    ]
