# Generated by Django 5.2.11 on 2026-02-26 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.tag')),
            ],
            bases=('catalog.tag',),
        ),
        migrations.CreateModel(
            name='ComplexityTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.tag')),
            ],
            bases=('catalog.tag',),
        ),
        migrations.CreateModel(
            name='ObjectiveTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.tag')),
            ],
            bases=('catalog.tag',),
        ),
        migrations.CreateModel(
            name='TriggerTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.tag')),
            ],
            bases=('catalog.tag',),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='product_media/')),
                ('url', models.URLField(blank=True, help_text='URL del video o imagen (e.g. YouTube, S3)', max_length=500, null=True)),
                ('is_video', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.systemproduct')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='systemproduct',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.actiontag'),
        ),
        migrations.AddField(
            model_name='systemproduct',
            name='complexities',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.complexitytag'),
        ),
        migrations.AddField(
            model_name='systemproduct',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.objectivetag'),
        ),
        migrations.AddField(
            model_name='systemproduct',
            name='triggers',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.triggertag'),
        ),
    ]
