# Generated by Django 5.2.11 on 2026-02-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tag_actiontag_complexitytag_objectivetag_triggertag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Niche',
        ),
        migrations.RemoveField(
            model_name='systemproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='systemproduct',
            name='niches',
            field=models.ManyToManyField(related_name='products', to='catalog.niche'),
        ),
    ]
