# Generated by Django 5.2.11 on 2026-02-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_category_niche_remove_systemproduct_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemproduct',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio original (tachado) para mostrar descuento', max_digits=10, null=True),
        ),
    ]
