# Generated by Django 5.2.11 on 2026-03-08 02:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, help_text='desktop, mobile, tablet', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer', models.URLField(blank=True, max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('utm_source', models.CharField(blank=True, help_text='Identificador del anunciante, sitio o publicación.', max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, help_text='Medio publicitario o de marketing (cpc, banner, email).', max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, help_text='Nombre de la campaña, lema o código promocional.', max_length=100, null=True)),
                ('utm_term', models.CharField(blank=True, help_text='Palabras clave de la búsqueda.', max_length=200, null=True)),
                ('utm_content', models.CharField(blank=True, help_text='Identificador de lo que se pulsó, útil para pruebas A/B.', max_length=200, null=True)),
                ('form_name', models.CharField(blank=True, help_text='Nombre del formulario donde dejó los datos.', max_length=100, null=True)),
                ('landing_page', models.URLField(blank=True, help_text='Página en la que aterrizó o dejó el lead.', max_length=2000, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas del equipo de ventas.', null=True)),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('CONTACTED', 'Contactado'), ('QUALIFIED', 'Calificado (MQL/SQL)'), ('DISQUALIFIED', 'Descartado'), ('CUSTOMER', 'Cliente')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor', models.ForeignKey(blank=True, help_text='Permite ver qué hizo el lead en la web antes de convertirse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='analytics.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(help_text='Ej: Video, Form, Button', max_length=100)),
                ('event_action', models.CharField(help_text='Ej: Play, Submit, Click', max_length=100)),
                ('event_label', models.CharField(blank=True, help_text='Ej: hero_video, contact_form', max_length=200, null=True)),
                ('event_data', models.JSONField(blank=True, help_text='Datos adicionales sobre el evento', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.pageview')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitor')),
            ],
        ),
    ]
